version: '3.3'

services:
  web:
    build: .
    links:
      - postgresql
      - redis
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .docker.env
    ports:
      - '5500:5500'
    environment:
      - PORT=5500
  migration:
    build:
      context: .
      dockerfile: migration.Dockerfile
    links:
      - postgresql
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .docker.env
    volumes:
      - ./prisma:/home/app/prisma
  postgresql:
    image: postgres:14
    env_file:
      - .docker.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - blog-cms-api-data-postgresql:/var/lib/postgresql/data
  redis:
    image: redis:7
    env_file:
      - .docker.env
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '6379:6379'
    volumes:
      - blog-cms-api-data-redis:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  blog-cms-api-data-postgresql:
  blog-cms-api-data-redis:
